import type { FastifyInstance } from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { config, isDevelopment } from '../../config/index.js';
import { logger } from '../../core/logger.js';
import type { SwaggerConfig } from './types.js';

const defaultConfig: SwaggerConfig = {
  title: 'Servcraft API',
  description: 'API documentation generated by Servcraft',
  version: '1.0.0',
  tags: [
    { name: 'Auth', description: 'Authentication endpoints' },
    { name: 'Users', description: 'User management endpoints' },
    { name: 'Health', description: 'Health check endpoints' },
  ],
};

export async function registerSwagger(
  app: FastifyInstance,
  customConfig?: Partial<SwaggerConfig>
): Promise<void> {
  const swaggerConfig = { ...defaultConfig, ...customConfig };

  await app.register(swagger, {
    openapi: {
      openapi: '3.0.3',
      info: {
        title: swaggerConfig.title,
        description: swaggerConfig.description,
        version: swaggerConfig.version,
        contact: swaggerConfig.contact,
        license: swaggerConfig.license,
      },
      servers: swaggerConfig.servers || [
        {
          url: `http://localhost:${config.server.port}`,
          description: 'Development server',
        },
      ],
      tags: swaggerConfig.tags,
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'Enter your JWT token',
          },
        },
      },
    },
  });

  await app.register(swaggerUi, {
    routePrefix: '/docs',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: true,
      displayRequestDuration: true,
      filter: true,
      showExtensions: true,
      showCommonExtensions: true,
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
  });

  logger.info('Swagger documentation registered at /docs');
}

// Helper to generate schema from Zod
export function zodToJsonSchema(zodSchema: unknown): Record<string, unknown> {
  // This is a simplified version - for full support use zod-to-json-schema package
  return {
    type: 'object',
    properties: {},
  };
}

// Common response schemas
export const commonResponses = {
  success: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      data: { type: 'object' },
    },
  },
  error: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string' },
      errors: {
        type: 'object',
        additionalProperties: {
          type: 'array',
          items: { type: 'string' },
        },
      },
    },
  },
  unauthorized: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string', example: 'Unauthorized' },
    },
  },
  notFound: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: false },
      message: { type: 'string', example: 'Resource not found' },
    },
  },
  paginated: {
    type: 'object',
    properties: {
      success: { type: 'boolean', example: true },
      data: {
        type: 'object',
        properties: {
          data: { type: 'array', items: { type: 'object' } },
          meta: {
            type: 'object',
            properties: {
              total: { type: 'number' },
              page: { type: 'number' },
              limit: { type: 'number' },
              totalPages: { type: 'number' },
              hasNextPage: { type: 'boolean' },
              hasPrevPage: { type: 'boolean' },
            },
          },
        },
      },
    },
  },
};

// Query parameters for pagination
export const paginationQuery = {
  type: 'object',
  properties: {
    page: { type: 'integer', minimum: 1, default: 1, description: 'Page number' },
    limit: { type: 'integer', minimum: 1, maximum: 100, default: 20, description: 'Items per page' },
    sortBy: { type: 'string', description: 'Field to sort by' },
    sortOrder: { type: 'string', enum: ['asc', 'desc'], default: 'asc', description: 'Sort order' },
    search: { type: 'string', description: 'Search query' },
  },
};

// ID parameter
export const idParam = {
  type: 'object',
  properties: {
    id: { type: 'string', format: 'uuid', description: 'Resource ID' },
  },
  required: ['id'],
};
